# Generated by Django 6.1 on 2026-08-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('python', 'Python'), ('django', 'Django'), ('gis', 'GIS / Spatial Analysis'), ('design', 'Graphic Design'), ('other', 'Other')], default='web', max_length=50)),
                ('technologies', models.CharField(blank=True, help_text='Example: HTML, CSS, JavaScript, Django', max_length=300)),
                ('project_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('completed', models.BooleanField(default=True)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
