# Generated by Django 6.1 on 2026-08-24 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_role', models.CharField(blank=True, max_length=150)),
                ('client_company', models.CharField(blank=True, max_length=150)),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('message', models.TextField()),
                ('rating', models.FloatField(choices=[(1.0, '1 Star'), (1.5, '1.5 Stars'), (2.0, '2 Stars'), (2.5, '2.5 Stars'), (3.0, '3 Stars'), (3.5, '3.5 Stars'), (4.0, '4 Stars'), (4.5, '4.5 Stars'), (5.0, '5 Stars')])),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
